apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ cookiecutter.name }}
  title: {{ cookiecutter.title }}
  description: {{ cookiecutter.description }}
  annotations:
    github.com/project-slug: vruggeri #{{ cookiecutter.destination.owner }}/{{ cookiecutter.destination.repo }}
spec:
  type: service
  lifecycle: development
  owner: {{ cookiecutter.owner }}
